sub/shows/urls.py
from django.conf.urls.defaults import *
from shows.models import Show
from transmeta import *
from tagging.views import tagged_object_list

info_dict = {
    'queryset': Show.objects.all().order_by("years"),
}

urlpatterns = patterns('shows.views',
    #shows
    url(r'^(?P<slug>[-\w]+)/edit/$', 'edit', name='show_edit'),
    url(r'^(?P<slug>[-\w]+)/delete/$', 'delete', name='show_delete'),
    url(r'^add/$', 'add', name='show_add'  ),
    #seasons 
    url(r'^(?P<slug>[-\w]+)/s(?P<season_num>[-\w]+)/$', 'season_details', name='season_item'),
    #url(r'^(?P<slug>[-\w]+)/s(?P<season_num>[-\w]+)/edit/$', 'season_edit', name='season_edit'),
    #episodes
    url(r'^(?P<slug>[-\w]+)/s(?P<season_num>[-\w]+?)/e(?P<episode_slug>[-\w]+?)/$', 'episode_details', name='episode_item'),
    
   
    #ajax calls
    url(r'^imdb_get_info/(?P<format>\w+)/(?P<show_id>\w+)/$','imdb_get_info', name ='show_imdb_get_info'),
    url(r'^imdb_search_by_title/(?P<format>\w+)/(?P<title>.*[^/])/$','imdb_search_by_title', name ='show_imdb_search_by_title'),
    url(r'^fill_show_episodes/(?P<format>\w+)/(?P<title>.*[^/])/$','fill_show_episodes', name ='fill_show_episodes'),
)

urlpatterns += patterns('django.views.generic.list_detail',
    url(r'^$', 'object_list', dict(info_dict, paginate_by=10), name='show_list'),
    url(r'^(?P<slug>[-\w]+)$', 'object_detail', dict(info_dict, slug_field='slug' ), name='show_item' ),
    
)

urlpatterns += patterns('',
    url(r'^tag/(?P<tag>[^/]+)/$', tagged_object_list, 
                dict(queryset_or_model=Show, paginate_by=10, allow_empty=True,
                template_object_name='object'), name='movie_list_by_tag' ),
    
)

sub/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from userprofile.views import get_profiles
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^sub/', include('sub.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
(r'^accounts/', include('userprofile.urls')),
    (r'^$', direct_to_template, {'extra_context': { 'profiles': get_profiles }, 'template': 'front.html'}),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^movies/', include('movies.urls')),
    (r'^actors/', include('persons.urls')),
    (r'^shows/', include('shows.urls')),
    (r'^search/', include('search.urls')),
    (r'^utils/', include('utils.urls')),
    (r'^news/', include('pressroom.urls')),
    (r'^subtitles/', include('subtitles.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),

)
# Serves media content. WARNING!! Only for development uses.
# On production use lighthttpd for media content.
if settings.SERV_STATIC is not None:

    # Delete the first trailing slash, if any.
    if settings.MEDIA_URL.startswith('/'):
        media_url = settings.MEDIA_URL[1:]
    else:
        media_url = settings.MEDIA_URL

    # Add the last trailing slash, if have not.
    if not media_url.endswith('/'):
        media_url = media_url + '/'

    urlpatterns += patterns('',
        (r'^' + media_url + '(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

sub/movies/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from utils.models import Genre , not_null_not_blank
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from userprofile.countries import CountryField
import os
from transmeta import TransMeta
from tagging.fields import TagField
from persons.models import Actor

#from djangoratings import RatingField

from django.utils.translation import ugettext_lazy as _ 
    
def get_image_posters_path(instance, filename):
    return os.path.join('posters', instance.slug, filename)

class Movie(models.Model):
    __metaclass__ = TransMeta
    
    title = models.CharField(verbose_name=_("The title"),
                                blank=False, null=True, max_length=250)
                               
    slug = models.SlugField(max_length=50, unique=True, blank=False, null=True)
    
    summary = models.TextField(verbose_name=_("The summary"),
                                    blank=False, null=True)
                                    
    publish_year = models.PositiveIntegerField(verbose_name=_("Publish year"), blank=True, null=True)
    
    creator = models.ForeignKey(User, verbose_name=_("Created by"),
                                blank=False, null=True)
    created = models.DateTimeField(verbose_name=_("Created at"),
                                   auto_now_add=True)
    
    #imdb info 
    imdb_url = models.URLField(verbose_name=_("IMDB Url"),verify_exists=False, blank=True, null=True)
    imdb_id = models.PositiveIntegerField(verbose_name=_("IMDB id"), blank=True, null=True)
    imdb_rating = models.DecimalField(verbose_name=_("IMDB Rating"), max_digits=4, decimal_places=2, blank=True, null=True)
    imdb_poster = models.URLField(verbose_name=_("IMDB Poster"),verify_exists=False, blank=True, null=True)
    genre = models.ManyToManyField(Genre, verbose_name=_("Genre"), blank=False, null=True, related_name='movies_in_genre')
    
    
    poster = models.ImageField(verbose_name=_("Poster"), upload_to=get_image_posters_path, blank=True, null=True)
    
    #rating = RatingField(range=5)
    
    # a fixed list of a changeable ?
    #lang =
    country = CountryField(verbose_name=_("Country"), null=True, blank=True)
    
    cast =  models.ManyToManyField(Actor, verbose_name=_("Cast"), null=True, blank=True, related_name='movie_acted_in')
    #producer =
    
    tags = TagField(verbose_name=_("Tags"))
        
        
    class Meta:
        translate = ('title', 'summary' )
        
    def save(self, *args, **kwargs):
        self.slug = slugify(getattr(self, 'title_en'))
        not_null_not_blank(self,('title_en', 'slug' ))
        super(Movie, self).save(*args, **kwargs)  
    
    
    def get_absolute_url(self):
        return reverse("movie_item", args=[self.slug])
    
    def __unicode__(self):
        # note that you can use name and description fields as usual
        return self.title

    def __str__(self):
        # compatibility
        return self.__unicode__()
    
    def imdb_rating_precentage(self):
        ''' retrun a percentage for the visual bar '''
        return str(self.imdb_rating  * 10 )

sub/shows/models.py
from django.db import models
from persons.models import Actor
from subtitles.models import Subtitle
from transmeta import TransMeta
from tagging.fields import TagField
from utils.models import Genre , not_null_not_blank
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
import os
from django.utils.translation import ugettext_lazy as _
    
def get_image_posters_path(instance, filename):
    return os.path.join('show-posters', instance.slug, filename)
    
class Show(models.Model):
    __metaclass__ = TransMeta
    
    #main fields
    title = models.CharField(verbose_name=_("The title"),
                                blank=False, null=True, max_length=250)
                               
    slug = models.SlugField(max_length=50, unique=True, blank=False, null=True)
    
    summary = models.TextField(verbose_name=_("The summary"),
                                    blank=False, null=True)
    
    poster = models.ImageField(verbose_name=_("Poster"), upload_to=get_image_posters_path, blank=True, null=True)
    
    genre = models.ManyToManyField(Genre, verbose_name=_("Genre"), blank=False, null=True, related_name='shows_in_genre')
    
    cast =  models.ManyToManyField(Actor, verbose_name=_("Cast"), null=True, blank=True, related_name='shows_acted_in')
    
    years = models.CharField(verbose_name=_("Running Years"), blank=False, null=True, max_length=50)
    
    #imdb fields
    
    imdb_id = models.PositiveIntegerField(verbose_name=_("IMDB id"), blank=True, null=True)
    imdb_rating = models.DecimalField(verbose_name=_("IMDB Rating"), max_digits=4, decimal_places=2, blank=True, null=True)
    imdb_poster = models.URLField(verbose_name=_("IMDB Poster"),verify_exists=False, blank=True, null=True)
    
    #admin fields
    creator = models.ForeignKey(User, verbose_name=_("Created by"),
                                blank=False, null=True)
    created = models.DateTimeField(verbose_name=_("Created at"),
                                   auto_now_add=True)                                
    tags = TagField(verbose_name=_("Tags"))
    #rating = RatingField(range=5)
    
    class Meta:
        translate = ('title', 'summary' )
    
    def save(self, *args, **kwargs):
        self.slug = slugify(getattr(self, 'title_en'))
        not_null_not_blank(self,('title_en', 'slug' ))
        super(Show, self).save(*args, **kwargs)  
    
    
    def get_absolute_url(self):
        return reverse("show_item", args=[self.slug])
    
    def __unicode__(self):
        # note that you can use name and description fields as usual
        return self.title

    def __str__(self):
        # compatibility
        return self.__unicode__()
        
    def imdb_url(self):
        if not (self.imdb_id == None):
            return 'http://www.imdb.com/title/tt' + str(self.imdb_id)
        else :
            return '#'
            
    def imdb_rating_precentage(self):
        ''' retrun a percentage for the visual bar '''
        return str(self.imdb_rating  * 10 )
    
    def seasons_orderd(self):
        return self.seasons.order_by('season_num')
        
class Season(models.Model):
    title = models.CharField(verbose_name=_("The title"),
                                blank=False, null=True, max_length=250)
    part_of = models.ForeignKey(Show, verbose_name=_("Belongs to"),
                                 blank=False, null=False, related_name='seasons')
    
    season_num = models.PositiveIntegerField(verbose_name=_("Season Number"), blank=True, null=True)
    
    def __unicode__(self):
        # note that you can use name and description fields as usual
        return u'' + self.part_of.title + u' S' + unicode(self.season_num)

    def __str__(self):
        # compatibility
        return self.__unicode__()
        
    def get_absolute_url(self):
        return reverse("season_item", args=[self.part_of.slug, "%02d" % self.season_num])
        
class Episode(models.Model):
    __metaclass__ = TransMeta
    title = models.CharField(verbose_name=_("The title"),
                                blank=False, null=True, max_length=250)
    summary = models.TextField(verbose_name=_("The summary"),
                                    blank=False, null=True)
    
    slug = models.SlugField(max_length=50, unique=False, blank=False, null=True)
    
    episode_num = models.PositiveIntegerField(verbose_name=_("Episode Number"), blank=True, null=True)    
    
    part_of = models.ForeignKey(Season, verbose_name=_("Belongs to"),
                                 blank=False, null=False, related_name='episodes')
                                 
    subtitles = models.ManyToManyField(Subtitle, verbose_name=_("Substitles"), null=True, blank=True, related_name='subtitle_of')
    
    class Meta:
        translate = ('title', 'summary' )
        
    def get_absolute_url(self):
        return reverse("episode_item", args=[self.part_of.part_of.slug, 
                                             "%02d" % self.part_of.season_num, 
                                             "%02d-%s" % (self.episode_num,self.slug),
                                             ])
    
    def save(self, *args, **kwargs):
        self.slug = slugify(getattr(self, 'title_en'))
        not_null_not_blank(self,('title_en', 'slug' ))
        super(Episode, self).save(*args, **kwargs) 
        
    def __unicode__(self):
        # note that you can use name and description fields as usual
        return u'' + str(self.part_of) + u'E' + unicode(self.episode_num) + ' "' + self.title +'"'

    def __str__(self):
        # compatibility
        return self.__unicode__()

sub/shows/forms.py
from django import forms
from shows.models import Show
from formfieldset.forms import FieldsetMixin
from django.forms.widgets import HiddenInput
from django.utils.translation import ugettext_lazy as _


class ShowForm(forms.ModelForm, FieldsetMixin):
    '''
    Profile Form. Composed by all the Profile model fields.
    '''
    cast = forms.CharField(required=False)
    genre = forms.CharField(required=False)
    fieldsets = (
                
                (_('English'),
                  {'fields': ('title_en','summary_en'), }),
                (_('Hebrew'),
                  {'fields': ('title_he','summary_he'), }),
                (_('Russian'),
                  {'fields': ('title_ru','summary_ru'), }),

                  (_('Show Details'), {'fields': ('tags',
                                                   'years',                  
                                                   'imdb_id', 
                                                   'imdb_rating',
                                                   'imdb_poster',
                                                   'cast',
                                                   'genre', 
                                                   'poster'),
                   'description': _('Your tags are shared')}),
                )
    
    
    _tmpl_p = (
        u'%(title)s<div>%(description)s%(fields)s</div>',
        u'<h3><a href="#">%s</a></h3>',
        u'<div class="description">%s</div>',
        u'<p>%(label)s %(field)s%(help_text)s</p>',
        u'%s',
        u'</p>',
        u' %s',
        True,
    )
    
    class Meta:
        model = Show
        exclude = ('slug', 'creator', )
    
    def __init__(self, *args, **kwrds):
        super(ShowForm,self).__init__(*args, **kwrds)
        self.fields['imdb_id'].widget = HiddenInput()
        self.fields['imdb_rating'].widget = HiddenInput()
        self.fields['imdb_poster'].widget = HiddenInput()
        
        self.fields['cast'].widget = HiddenInput()
        self.fields['cast'].value = ''
        
        self.fields['genre'].widget = HiddenInput()
        self.fields['genre'].value = ''
        
    def clean_title(self):
        title = self.cleaned_data['title_en']
        if title == '':
            raise forms.ValidationError(_("title can't be empty"))
        try:
            show = Show.objects.get(title=title)
        except Show.DoesNotExist:
            return show
        raise forms.ValidationError(_('%s already exists') % title )

sub/shows/templates/shows/episode_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Details for " %} {{ object.title }}{% endblock %}
{% block extracss %}
{% endblock %}

{% block content %}
<p>
<h1>{{ object.title }}</h1>
<h3>[ <a href="{{ object.part_of.part_of.get_absolute_url }}">{{object.part_of.part_of.title }}</a>: {% trans "Season"%} {{ object.part_of.season_num }} {% trans "Episode"%} {{ object.episode_num }} ] </h3>
{{ object.summary }}
{% for subtitle in object.subtitles.all %}
<h3><a href="{{ MEDIA_URL}}{{subtitle.sub_file}}"> {{ subtitle.version }}</a></h3>
{% endfor %}  <br/>
    
</p>
{% endblock %}

sub/shows/templates/shows/season_detail.html
<ol>
    {% for ch in object.episodes.all %}
    <li><a href="{{ ch.get_absolute_url }}">{{ ch.title }}</a></li>
    {% endfor %}
</ol>

sub/shows/templates/shows/show_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load comments %}

{% block title %}{% trans "Details for " %} {{ object.title }}{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-ui-1.6.custom.min.js"></script>

<script type="text/javascript">
  $(document).ready(function(){
    $("#tabs").tabs();
    $("#add_comments").toggle();
    
    $('input#add_comment').click(function () {
      $('#add_comments').toggle();
      var target_top = 1000;
      $('html, body').animate({scrollTop:target_top}, 500);
    });
    
  });
  

</script>
  
{% endblock %}
{% block extracss %}
    <link rel="stylesheet" href="{{ MEDIA_URL}}css/ui.all.css" type="text/css" />
    <style>
        #id_honeypot {
        display: none;
        }
        {% if LANGUAGE_BIDI %}
        img.poster{ 
            float: right; 
            margin: 1.5em 1.5em 1.5em 1.5em;
            } 
        {% endif %}
        a.edit{color:red;font-size:40%} 
        
        span.progress-container {
             display:inline-block;
             width:200px;
             height:20px;
             background-color: rgb(146, 183, 211);

        }

        div.progress-inner {

             height:20px;
             background-color:rgb(91, 147, 191);
             border-right:1px white
             solid;
        }
        div.title {
            {% if LANGUAGE_BIDI %}
                padding-right: 4px;
            {% else %}
                padding-left: 4px;
            {% endif %}
               margin-top: -20px; color: #DDD;
        }
        div.rating {
               {% if LANGUAGE_BIDI %}
                text-align: left; 
                padding-left: 4px;
               {% else %}
                text-align: right; 
                padding-right: 4px;
               {% endif %}
               margin-top: -18px; color: #DDD; padding-right: 4px;
        }
        img.imdb-icon {
            {% if LANGUAGE_BIDI %}
                float: right;
            {% endif %}
           margin:auto;
        }
        
        input#add_comment {
        padding: 5px;
        font-family: Helvetica, sans-serif;
        font-size: 1.4em;
        margin: 0px 0px 10px 0px;
        border: 2px solid #ccc;
               
        width: 150px;
        font-size: 1.3em;
        margin-left: 15px;
        margin-bottom: 15px;
        
        }

    </style>
{% endblock %}

{% block content %}
	<h1>{{ object.title }} <a class="edit" href="{{ object.get_absolute_url }}/edit/">[{% trans "Edit" %}]</a> </h1>  
    <p> {% if object.poster %}
            <img class="poster" src="{{ object.poster.url }}"/>   
        {% endif %}
        
    {{ object.summary }}</p>
    
    <p><a href="{{ object.imdb_url }}"><img class="imdb-icon" src="{{ MEDIA_URL }}images/imdb.gif" alt="loading..."/></a></p>


    <span class="progress-container">
       <div style="width: {{ object.imdb_rating_precentage }}% " class="progress-inner"></div>
       <div class="title"> {% trans "IMDB Rating" %} </div>
       <div class="rating">{{ object.imdb_rating }}/10</div>
    </span>
    <br/>
    {% trans "Genre" %}: 
    {% for genre in object.genre.all %}
        {{ genre.name }} ,
    {% endfor %}  <br/>
    
    {% trans "Cast" %}: 
    {% for actor in object.cast.all %}
        <a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a> ,
    {% endfor %}
    <br/>
  
    <br /><br /><br />
  
    {% trans "Episodes Guide" %}:
    <br />
    <div id="tabs">
        <ul>
        {% for season in object.seasons_orderd %}
            <li><a href="{{ season.get_absolute_url }}">{% trans "Season" %} {{ season.season_num }}</a></li>
        {% endfor %}
        </ul>
    </div>
    
    <div>{% render_comment_list for object %}</div>
    <input type="submit" id="add_comment" value='{% trans "Add Comment" %}'/>    
    <div id="add_comments">{% render_comment_form for object%}
        
    </div>

{% endblock %}

sub/shows/templates/shows/show_edit.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Add/Edit Movie Details" %}{% endblock %}
{% block extracss %}
    <style>
         label
        {
            width: 10em;
            margin-right: 0.em;
            position: relative;
            background:#F4F4F8;
            {% if LANGUAGE_BIDI %}
            text-align: right;
            float: right;
            {% else %}
            float: left;
            text-align: left;
            {% endif %}
        
        }

        .submit input
        {
                        
            margin-left: 4.5em;
        }
        input, button {
         padding: 5px;
            font-family: Helvetica, sans-serif;
            font-size: 1.4em;
            margin: 0px 0px 10px 0px;
            border: 2px solid #ccc;
                   
            width: 150px;
            font-size: 1.3em;
            margin-left: 15px;
            margin-bottom: 15px;
        }
        
        
    </style>
{% endblock %}
{% block extrajs %}
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>

<script type="text/javascript">

$(document).ready(function() { 
	
    $("span#loading").toggle();
    
    // ------------- make collapsable ---------------------------------
     $("#accordion").accordion();
    
    // ----------- populate episode info --------------------------- 
    $('button#populate').click(function () { 
        var value = $('input#id_title_en').val();
        if (value != '') {
            clearErrorsAndShowList()
            populateByTitle(value);
        } else {
            $("div#error").text("English title is empty");
        }
    });
    
    function populateByTitle(title) {
        
        $.ajax({
            type: "GET",
            url: "/shows/fill_show_episodes/json/"+title+"/",
            dataType:  'json',
            success:   processPopulateInfo,
            beforeSend:  setLoading, 
            error: processErrors,
        });
    }
    
    function processPopulateInfo(data) {
        clearLoading();
    }
     
    // --------------------- find imdb info -----------------------
    $('button#imdb').click(function () { 
        var value = $('input#id_title_en').val();
        if (value != '') {
            clearErrorsAndShowList()
            findByTitle(value);
        } else {
            $("div#error").text("English title is empty");
        }
    });
    
     function get_task_status(task_id, callback)
    {
        $.get("/utils/task-stat/"+task_id+"/", {}  ,
            function(data){
                if (data.task.status == 'SUCCESS') {
                    callback( data.task.result);
                } else{
                    setTimeout(get_task_status,  500, task_id, callback);
                }
            },  'json' );
    }

    function findByID(value) {
        
        $.ajax({
            type: "GET",
            url: "/shows/imdb_get_info/json/"+value+"/",
            dataType:  'json',
            success:   wait_for_ShowData,
            beforeSend:  setLoading, 
            error: processErrors
        });
    }
    function  wait_for_ShowData(data)
    {
        get_task_status(data.task_id, processShowData)
    }
    function processShowData(data) {
        if (data.error) {
            $("div#error").text("Error in getting info, try again later...");
        } else {
        
            $("input#id_title_en").val(data.title);
            $("textarea#id_summary_en").val(data.plot);
            $("input#id_imdb_url").val(data.imdb_url);
            $("input#id_imdb_rating").val(data.rating);
            $("input#id_imdb_poster").val(data.cover_url);
            $("input#id_years").val(data.years);
            $("input#id_cast").val(data.cast);
            $("input#id_genre").val(data.genre);
        }
        clearLoading();
    }
    


    function findByTitle(title) {
      
        $.ajax({
            type: "GET",
            url: "/shows/imdb_search_by_title/json/"+title+"/",
            dataType:  'json',
            success:  wait_for_Showlist,
            beforeSend:  setLoading, 
            error: processErrors
        });
    }
    
    function  wait_for_Showlist(data)
    {
        get_task_status(data.task_id, processShowList)
    }

    function processShowList(data) {
        if (data.error) {
            $("div#error").text("Error in getting info, try again later...");
        } else {
            $.each(data.list, function(i,item){
                    $("<a/>").text(item.title).appendTo("#showlist").bind("click", {id:item.id},function(e){
                            clearErrors()
                            $("input#id_imdb_id").val(e.data.id);
                            findByID(e.data.id);
                            }).wrap("<li/>");
                    if ( i == 9 ) return false; });
            
            
        }
        clearLoading();
    }
    
    
    function setLoading(data) {
        $("span#loading").show();
    }
    function clearLoading() {
        $("span#loading").hide();
    }
    function clearErrorsAndShowList() {
        $("div#error").text("");
        $("ol#showlist").text("");
    }
    function clearErrors() {
        $("div#error").text("");
    }
    
    function processErrors(errors) {
        $("div#error").text("Error");
        $("div#error").append(errors.responseText);
    }
    


});

</script>
{% endblock %}

{% block content %}
    
    <button type="" id="imdb">{% trans 'Get IMDB Data' %}</button>
    {% if edit %} <button type="" id="populate">{% trans 'Populate Episodes' %}</button>{% endif %}
    <span id="loading">
       <img src="{{ MEDIA_URL }}images/loading3.gif" alt="loading..."/> {% trans 'Loading data from IMDB' %} 
    </span>

    <div id="error"></div>  
     <ol id="showlist"></ol>
    
    <form enctype="multipart/form-data" action="{{ request.path_info }}" method="post">{% csrf_token %}
        {{ form.errors }}
        <div id="accordion"> {{ form.as_fieldset_p }} </div>
        <input type="submit" value="{% trans 'Save' %}" />
	</form>
    
{% endblock %}

sub/shows/templates/shows/show_list.html
{% extends "base.html" %}
{% load i18n %}
{% load tagging_tags %}
{% load pagers %}

{% block title %}{% trans "TV Shows List" %}{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.confirm-1.2.js"></script>

<script type="text/javascript">
	$(function() {
    //del a movie
		$("a.del").click(function() {
            $.getJSON($(this).attr("href"), function(data) {
				if (data.success) {
					//TODO animate the 
                    $("h2."+data.slug).hide();
                    window.location.reload()
				} else { alert('delete failure'); }
			});
			return false;
		}).confirm(
        {
           msg:'{% trans "Are you sure?" %}',
            timeout:3000,
            buttons: {
                ok:'{% trans "yes" %}',
                cancel:'{% trans "no" %}',
            }
        }
        );

        
    
	});
</script>
{% endblock %}

{% block extracss %}
<style>
        a.my1{color:red;font-size:40%} 
        a.del{color:red;font-size:40%} 
        a.tag{color:green;} 
        div.tag_title{color:black;font-size:40%} 
        
       .pager {
          padding-top: 20px;
          padding-left: 40px;
          }
       .pager .page a {
          border: 3px solid #bbbbbb;
          margin-left: 1px;
          margin-right: 1px;
          padding-left: 4px;
          padding-right: 4px;
          text-decoration: none;
          color: #000000;
          }
       .pager .current {
          border: 3px solid #444444;
          margin-left: 2px;
          margin-right: 2px;
          padding-left: 2px;
          }

</style>
{% endblock %}

{% block content %}

	{% if tag %}
        <h1>{% trans "List of all Shows tagged" %}: {{ tag }}</h1>
    {% else %}
        <h1>{% trans "List of all Shows" %}</h1>
    {% endif %}
   
    <a href="/shows/add/">{% trans "Add Show" %}</a>
     {% if is_paginated %}{% paginator 3 %}{% endif %}
    {% for show in object_list %}
        <h2 class='{{ show.slug }}'>
        {{ forloop.counter }}. 
          <a href="{{ show.get_absolute_url }}">{{ show.title }}</a> [{{ show.years }}]
          <a class="my1" href="{{ show.get_absolute_url }}/edit/">[{% trans "Edit" %}]</a>
          <a class="del" href="{{ show.get_absolute_url }}/delete/">[{% trans "Delete" %}]</a>
          <div class="tag_title">{% trans "Tags" %}:
              {% tags_for_object show as tag_list %}
              {% for tag in tag_list %}
                <a class="tag" href="/shows/tag/{{ tag }}">{{ tag }}</a>,
              {% endfor %}
          </div>
          
        </h2>
    {% endfor %}
    {% if is_paginated %}{% paginator 3 %}{% endif %}
    <div class = 'errors'></div>
    
{% endblock %}