sub/movies/urls.py
from django.conf.urls.defaults import *
from movies.models import Movie
from transmeta import *
from tagging.views import tagged_object_list

info_dict = {
    'queryset': Movie.objects.all().order_by("publish_year"),
}

urlpatterns = patterns('movies.views',
    url(r'^(?P<slug>[-\w]+)/edit/$', 'edit', name='movie_edit'),
    url(r'^(?P<slug>[-\w]+)/delete/$', 'delete', name='movie_delete'),
    url(r'^add/$', 'add', name='movie_add'  ),
    url(r'^imdb_get_info/(?P<format>\w+)/(?P<movie_id>\w+)/$','imdb_get_info', name ='movie_imdb_get_info'),
    url(r'^imdb_search_by_title/(?P<format>\w+)/(?P<title>.*[^/])/$','imdb_search_by_title', name ='movie_imdb_search_by_title'),
)

urlpatterns += patterns('django.views.generic.list_detail',
    url(r'^$', 'object_list', dict(info_dict, paginate_by=10), name='movie_list'),
    url(r'^(?P<slug>[-\w]+)$', 'object_detail', dict(info_dict, slug_field='slug' ), name='movie_item' ),
    
)

urlpatterns += patterns('',
    url(r'^tag/(?P<tag>[^/]+)/$', tagged_object_list, 
                dict(queryset_or_model=Movie, paginate_by=10, allow_empty=True,
                template_object_name='object'), name='movie_list_by_tag' ),
    
)

sub/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from userprofile.views import get_profiles
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^sub/', include('sub.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
(r'^accounts/', include('userprofile.urls')),
    (r'^$', direct_to_template, {'extra_context': { 'profiles': get_profiles }, 'template': 'front.html'}),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^movies/', include('movies.urls')),
    (r'^actors/', include('persons.urls')),
    (r'^shows/', include('shows.urls')),
    (r'^search/', include('search.urls')),
    (r'^utils/', include('utils.urls')),
    (r'^news/', include('pressroom.urls')),
    (r'^subtitles/', include('subtitles.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),

)
# Serves media content. WARNING!! Only for development uses.
# On production use lighthttpd for media content.
if settings.SERV_STATIC is not None:

    # Delete the first trailing slash, if any.
    if settings.MEDIA_URL.startswith('/'):
        media_url = settings.MEDIA_URL[1:]
    else:
        media_url = settings.MEDIA_URL

    # Add the last trailing slash, if have not.
    if not media_url.endswith('/'):
        media_url = media_url + '/'

    urlpatterns += patterns('',
        (r'^' + media_url + '(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

sub/movies/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from utils.models import Genre , not_null_not_blank
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from userprofile.countries import CountryField
import os
from transmeta import TransMeta
from tagging.fields import TagField
from persons.models import Actor

#from djangoratings import RatingField

from django.utils.translation import ugettext_lazy as _ 
    
def get_image_posters_path(instance, filename):
    return os.path.join('posters', instance.slug, filename)

class Movie(models.Model):
    __metaclass__ = TransMeta
    
    title = models.CharField(verbose_name=_("The title"),
                                blank=False, null=True, max_length=250)
                               
    slug = models.SlugField(max_length=50, unique=True, blank=False, null=True)
    
    summary = models.TextField(verbose_name=_("The summary"),
                                    blank=False, null=True)
                                    
    publish_year = models.PositiveIntegerField(verbose_name=_("Publish year"), blank=True, null=True)
    
    creator = models.ForeignKey(User, verbose_name=_("Created by"),
                                blank=False, null=True)
    created = models.DateTimeField(verbose_name=_("Created at"),
                                   auto_now_add=True)
    
    #imdb info 
    imdb_url = models.URLField(verbose_name=_("IMDB Url"),verify_exists=False, blank=True, null=True)
    imdb_id = models.PositiveIntegerField(verbose_name=_("IMDB id"), blank=True, null=True)
    imdb_rating = models.DecimalField(verbose_name=_("IMDB Rating"), max_digits=4, decimal_places=2, blank=True, null=True)
    imdb_poster = models.URLField(verbose_name=_("IMDB Poster"),verify_exists=False, blank=True, null=True)
    genre = models.ManyToManyField(Genre, verbose_name=_("Genre"), blank=False, null=True, related_name='movies_in_genre')
    
    
    poster = models.ImageField(verbose_name=_("Poster"), upload_to=get_image_posters_path, blank=True, null=True)
    
    #rating = RatingField(range=5)
    
    # a fixed list of a changeable ?
    #lang =
    country = CountryField(verbose_name=_("Country"), null=True, blank=True)
    
    cast =  models.ManyToManyField(Actor, verbose_name=_("Cast"), null=True, blank=True, related_name='movie_acted_in')
    #producer =
    
    tags = TagField(verbose_name=_("Tags"))
        
        
    class Meta:
        translate = ('title', 'summary' )
        
    def save(self, *args, **kwargs):
        self.slug = slugify(getattr(self, 'title_en'))
        not_null_not_blank(self,('title_en', 'slug' ))
        super(Movie, self).save(*args, **kwargs)  
    
    
    def get_absolute_url(self):
        return reverse("movie_item", args=[self.slug])
    
    def __unicode__(self):
        # note that you can use name and description fields as usual
        return self.title

    def __str__(self):
        # compatibility
        return self.__unicode__()
    
    def imdb_rating_precentage(self):
        ''' retrun a percentage for the visual bar '''
        return str(self.imdb_rating  * 10 )

sub/movies/forms.py
from django import forms
from movies.models import Movie
from formfieldset.forms import FieldsetMixin
from django.forms.widgets import HiddenInput
from django.utils.translation import ugettext_lazy as _


class MovieForm(forms.ModelForm, FieldsetMixin):
    '''
    Profile Form. Composed by all the Profile model fields.
    '''
    cast = forms.CharField(required=False)
    genre = forms.CharField(required=False)
    fieldsets = (
                
                (_('English'),
                  {'fields': ('title_en','summary_en'), }),
                (_('Hebrew'),
                  {'fields': ('title_he','summary_he'), }),
                (_('Russian'),
                  {'fields': ('title_ru','summary_ru'), }),
                  
                  (_('Movie Details'), {'fields': ('tags', 
                                                   'country',
                                                   'publish_year', 
                                                   'imdb_id', 
                                                   'imdb_url', 
                                                   'imdb_rating',
                                                   'imdb_poster',
                                                   'cast',
                                                   'genre', 
                                                   'poster'),
                   'description': _('Your tags are shared')}),
                )
    
    _tmpl_p = (
        u'%(title)s<div>%(description)s%(fields)s</div>',
        u'<h3><a href="#">%s</a></h3>',
        u'<div class="description">%s</div>',
        u'<p>%(label)s %(field)s%(help_text)s</p>',
        u'%s',
        u'</p>',
        u' %s',
        True,
    )
    #TODO: fix the form to look like http://www.webdesignerwall.com/demo/jquery/accordion1.html

    class Meta:
        model = Movie
        exclude = ('slug', 'creator', )
    
    def __init__(self, *args, **kwrds):
        super(MovieForm,self).__init__(*args, **kwrds)
        self.fields['imdb_id'].widget = HiddenInput()
        self.fields['imdb_url'].widget = HiddenInput()
        self.fields['imdb_rating'].widget = HiddenInput()
        self.fields['imdb_poster'].widget = HiddenInput()
        
        self.fields['cast'].widget = HiddenInput()
        self.fields['cast'].value = ''
        
        self.fields['genre'].widget = HiddenInput()
        self.fields['genre'].value = ''
        
    def clean_title(self):
        title = self.cleaned_data['title_en']
        if title == '':
            raise forms.ValidationError(_("title can't be empty"))
        try:
            mobie = Movie.objects.get(title=title)
        except Movie.DoesNotExist:
            return mobie
        raise forms.ValidationError(_('%s already exists') % title )

sub/movies/views.py
# Create your views here.
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from movies.models import Movie
from movies.forms import MovieForm
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
import json
from datetime import datetime
from utils.helper import save_poster, add_cast ,add_genre
from utils.imdb_ext import *
from utils.tasks import findMovieByTitleTask, findMovieByIDTask
            
@login_required
def edit(request, slug):
    '''
    Edit movie info
    '''
    movie, created = Movie.objects.get_or_create(slug=slug)
    
    if request.method == "POST":
        form = MovieForm(request.POST, request.FILES, instance=movie)
        if form.is_valid():
            obj = form.save(commit=False)
            
            if obj.imdb_poster:
                save_poster(obj, obj.imdb_poster)
                add_cast(obj, form.data['cast'], request.user)
                add_genre(obj, form.data['genre'])

            obj.save()
            return HttpResponseRedirect(reverse("movie_item", args=[obj.slug]))
    else:
        form = MovieForm(instance=movie)
        
    template = 'movies/edit.html'
    data = { 'form': form, }
    
    return render_to_response(template, data , context_instance=RequestContext(request))

@login_required
def add(request):
    '''
    Add new movie info
    '''  
    
    if request.method == "POST":
        form = MovieForm(request.POST, request.FILES)
        
        if form.is_valid():
            obj = form.save(commit=False)
            obj.creator = request.user
            obj.created = datetime.now()
            obj.save()
            if obj.imdb_poster:
                save_poster(obj, obj.imdb_poster)
            try:
                add_cast(obj, form.data['cast'], request.user)
            except:
	         pass
            try:
                add_genre(obj, form.data['genre'])
            except:
	         pass    
            obj.save()
            return HttpResponseRedirect(reverse("movie_item", args=[obj.slug]))
    else:
        form = MovieForm()
        
    template = 'movies/edit.html'
    data = { 'form': form, }
    
    return render_to_response(template, data , context_instance=RequestContext(request))
    
@login_required
def delete(request, slug):
    '''
    remove movie from db
    '''
    if request.is_ajax():
        movie, created = Movie.objects.get_or_create(slug=slug)
        
        try:
            movie.delete()
            return HttpResponse(json.dumps({'success': True, 'slug':slug}))
        except:
            return HttpResponse(json.dumps({'success': False, 'slug':slug}))
    else:
        raise Http404()
        
@login_required
def imdb_get_info(request, format, movie_id):
    '''
    search a movie in imdb by it's id
    '''
    if request.is_ajax():
        info = {}
        task = findMovieByIDTask.delay(movie_id)
        info["task_id"] = task.task_id
 
        if format == 'xml':
            mimetype = 'application/xml'
            #TODO xml serialize
            data = 'Not implemented'
        if format == 'json':
            mimetype = 'application/javascript'
            data = json.dumps(info)

        return HttpResponse(data ,mimetype)
    # If you want to prevent non XHR calls
    else:
        return HttpResponse(status=400)

@login_required
def imdb_search_by_title(request, format, title):
    '''
    search a movie in imdb by title, and send back a list with names & imdb ids
    '''
    if request.is_ajax():
        info = {}
        task = findMovieByTitleTask.delay(title, filter=None)
        info["task_id"] = task.task_id
            
        if format == 'xml':
            mimetype = 'application/xml'
            #TODO xml serialize
            data = 'Not implemented'
        if format == 'json':
            mimetype = 'application/javascript'
            data = json.dumps(info)

        return HttpResponse(data ,mimetype)
    # If you want to prevent non XHR calls    
    else:
        return HttpResponse(status=400)
        

sub/movies/templates/movies/edit.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Add/Edit Movie Details" %}{% endblock %}
{% block extracss %}
    <style>
        
        label
        {
            width: 10em;
            margin-right: 0.em;
            position: relative;
            background:#F4F4F8;
            {% if LANGUAGE_BIDI %}
            text-align: right;
            float: right;
            {% else %}
            float: left;
            text-align: left;
            {% endif %}
        }

        .submit input
        {
                        
            margin-left: 4.5em;
        }
        
        input, button {
         padding: 5px;
            font-family: Helvetica, sans-serif;
            font-size: 1.4em;
            margin: 0px 0px 10px 0px;
            border: 2px solid #ccc;
                   
            width: 150px;
            font-size: 1.3em;
            margin-left: 15px;
            margin-bottom: 15px;
        }
    </style>
{% endblock %}
{% block extrajs %}
<link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
  
<script type="text/javascript">

$(document).ready(function() { 
    $("span#loading").toggle();
    
    $("#accordion").accordion();
    $('button#imdb').click(function () { 
        var value = $('input#id_title_en').val();
        if (value != '') {
            clearErrorsAndMovieList()
            findByTitle(value);
        } else {
            $("div#error").text("English title is empty");
        }
    });
    
    
    function get_task_status(task_id, callback)
    {
        $.get("/utils/task-stat/"+task_id+"/", {}  ,
            function(data){
                if (data.task.status == 'SUCCESS') {
                    callback( data.task.result);
                } else{
                    setTimeout(get_task_status,  500, task_id, callback);
                }
            },  'json' );
    }
    
    function findByID(value) {
        
        $.ajax({
            type: "GET",
            url: "/movies/imdb_get_info/json/"+value+"/",
            dataType:  'json',
            success:   wait_for_moviedata,
            beforeSend:  setLoading, 
            error: processErrors,
        });
    }
    
    function  wait_for_moviedata(data)
    {
        get_task_status(data.task_id, processMovieData)
    }
    
    function processMovieData(data) {
        if (data.error) {
            $("div#error").text("Error in getting info, try again later...");
        } else {
        
            $("input#id_title_en").val(data.title);
            $("textarea#id_summary_en").val(data.plot);
            $("input#id_imdb_url").val(data.imdb_url);
            $("input#id_imdb_rating").val(data.rating);
            $("input#id_imdb_poster").val(data.cover_url);
            $("input#id_publish_year").val(data.year);
            $("input#id_cast").val(data.cast);
            $("input#id_genre").val(data.genre);
        }
        clearLoading();
    }
    
    
    function findByTitle(title) {
        
        $.ajax({
            type: "GET",
            url: "/movies/imdb_search_by_title/json/"+title+"/",
            dataType:  'json',
            success:   wait_for_movielist,
            beforeSend:  setLoading, 
            error: processErrors,
        });
    }
    
    function  wait_for_movielist(data)
    {
        get_task_status(data.task_id, processMovieList)
    }
    
    function processMovieList(data) {
        if (data.error) {
            $("div#error").text("Error in getting info, try again later...");
        } else {
            $.each(data.list, function(i,item){
                    $("<a/>").text(item.title).appendTo("#movielist").bind("click", {id:item.id},function(e){
                            clearErrors()
                            $("input#id_imdb_id").val(e.data.id);
                            findByID(e.data.id);
                            }).wrap("<li/>");
                    if ( i == 9 ) return false; });
            
            
        }
        clearLoading();
    }
    
    
    function setLoading(data) {
        $("span#loading").toggle();
    }
    function clearLoading() {
        $("span#loading").toggle();
    }
    function clearErrorsAndMovieList() {
        $("div#error").text("");
        $("ol#movielist").text("");
    }
    function clearErrors() {
        $("div#error").text("");
    }
    
    function processErrors(errors) {
        alert(errors.status )
        alert(errors.responseText )
        $("div#error").text("Error");
        $("div#error").append(errors.responseText);
    }
    


});

</script>
{% endblock %}

{% block content %}
    
    <button type="" id="imdb">{% trans 'Get IMDB Data' %}</button>
    <span id="loading">
       <img src="{{ MEDIA_URL }}images/loading3.gif" alt="loading..."/> {% trans 'Loading data from IMDB' %} 
    </span>

    <div id="error"></div>  
    <ol id="movielist"></ol>  
    
    <form enctype="multipart/form-data" action="{{ request.path_info }}" method="post">{% csrf_token %}
        {{ form.errors }}
        <div id="accordion"> {{ form.as_fieldset_p }} </div>
        <input type="submit" value="{% trans 'Save' %}" />
	</form>
    
{% endblock %}

sub/movies/templates/movies/movie_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load comments %}

{% block title %}{% trans "Details for " %} {{ object.title }}{% endblock %}
{% block extracss %}
    <style>
        {% if LANGUAGE_BIDI %}
        img.poster{ 
            float: right; 
            margin: 1.5em 1.5em 1.5em 1.5em;
            } 
        {% endif %}
        a.edit{color:red;font-size:40%} 
        
        span.progress-container {
             display:inline-block;
             width:200px;
             height:20px;
             background-color: rgb(146, 183, 211);

        }

        div.progress-inner {

             height:20px;
             background-color:rgb(91, 147, 191);
             border-right:1px white
             solid;
        }
        div.title {
            {% if LANGUAGE_BIDI %}
                padding-right: 4px;
            {% else %}
                padding-left: 4px;
            {% endif %}
               margin-top: -20px; color: #DDD;
        }
        div.rating {
               {% if LANGUAGE_BIDI %}
                text-align: left; 
                padding-left: 4px;
               {% else %}
                text-align: right; 
                padding-right: 4px;
               {% endif %}
               margin-top: -18px; color: #DDD; padding-right: 4px;
        }
        img.imdb-icon {
            {% if LANGUAGE_BIDI %}
                float: right;
            {% endif %}
           margin:auto;
        }
        
        input#add_comment {
        padding: 5px;
        font-family: Helvetica, sans-serif;
        font-size: 1.4em;
        margin: 0px 0px 10px 0px;
        border: 2px solid #ccc;
               
        width: 150px;
        font-size: 1.3em;
        margin-left: 15px;
        margin-bottom: 15px;
        
        }
    </style>
{% endblock %}
{% block extrajs %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-ui-1.6.custom.min.js"></script>
<script type="text/javascript">
  $(document).ready(function(){
    $("#tabs").tabs();
    $("#add_comments").toggle();
    
    $('input#add_comment').click(function () {
      $('#add_comments').toggle();
      var target_top = 1000;
      $('html, body').animate({scrollTop:target_top}, 500);
    });
    
  });
  

</script>
{% endblock %}

{% block content %}
    <h1>{{ object.title }} <a class="edit" href="{{ object.get_absolute_url }}/edit/">[{% trans "Edit" %}]</a> </h1>  
    <p> {% if object.poster %}
            <img class="poster" src="{{ object.poster.url }}"/>   
        {% endif %}
        
    {{ object.summary }}</p>
    
    <p><a href="{{ object.imdb_url }}"><img class="imdb-icon" src="{{ MEDIA_URL }}images/imdb.gif" alt="loading..."/></a></p>
        
    <span class="progress-container">
       <div style="width: {{ object.imdb_rating_precentage }}% " class="progress-inner"></div>
       <div class="title"> {% trans "IMDB Rating" %} </div>
       <div class="rating">{{ object.imdb_rating }}/10</div>
    </span>
    
    <p>{% trans "Cast" %}: 
    {% for actor in object.cast.all %}
        <a href="{{ actor.get_absolute_url }}">{{ actor.name }}</a> ,
    {% endfor %} <br/>
    {% trans "Genre" %}: 
    {% for genre in object.genre.all %}
        {{ genre.name }} ,
    {% endfor %}
    </p>
    
    <div>{% render_comment_list for object %}</div>
    <input type="submit" id="add_comment" value='{% trans "Add Comment" %}'/>    
    <div id="add_comments">{% render_comment_form for object%}
        
    </div>

{% endblock %}