sub/persons/urls.py
from django.conf.urls.defaults import *
from persons.models import Actor
from transmeta import *
from tagging.views import tagged_object_list

info_dict = {
    'queryset': Actor.objects.all().order_by('name_en'),
}

urlpatterns = patterns('persons.views',
    url(r'^(?P<slug>[-\w]+)/edit/$', 'actor_edit', name='actor_edit'),
    url(r'^(?P<slug>[-\w]+)/delete/$', 'actor_delete', name='actor_delete'),
    url(r'^add/$', 'actor_add', name='actor_add'  ),
    url(r'^imdb_get_info/(?P<format>\w+)/(?P<person_id>\w+)/$','imdb_get_info', name ='per_imdb_get_info'),
    url(r'^imdb_search_by_name/(?P<format>\w+)/(?P<name>.*[^/])/$','imdb_search_by_name', name ='per_imdb_search_by_name'),
    url(r'^edb_translate_name/(?P<format>\w+)/(?P<name>.*[^/])/$','edb_translate_name', name ='edb_translate_name'),

)

urlpatterns += patterns('django.views.generic.list_detail',
    url(r'^$', 'object_list', dict(info_dict,paginate_by=10) , name='actor_list'),
    url(r'^(?P<slug>[-\w]+)$', 'object_detail', dict(info_dict, slug_field='slug' ), name='actor_item' ),    
)

urlpatterns += patterns('',
    url(r'^tag/(?P<tag>[^/]+)/$', tagged_object_list, 
                dict(queryset_or_model=Actor, paginate_by=10, allow_empty=True,
                template_object_name='object'), name='actor_list_by_tag' ),
    
)

sub/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from userprofile.views import get_profiles
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^sub/', include('sub.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
(r'^accounts/', include('userprofile.urls')),
    (r'^$', direct_to_template, {'extra_context': { 'profiles': get_profiles }, 'template': 'front.html'}),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^movies/', include('movies.urls')),
    (r'^actors/', include('persons.urls')),
    (r'^shows/', include('shows.urls')),
    (r'^search/', include('search.urls')),
    (r'^utils/', include('utils.urls')),
    (r'^news/', include('pressroom.urls')),
    (r'^subtitles/', include('subtitles.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),

)
# Serves media content. WARNING!! Only for development uses.
# On production use lighthttpd for media content.
if settings.SERV_STATIC is not None:

    # Delete the first trailing slash, if any.
    if settings.MEDIA_URL.startswith('/'):
        media_url = settings.MEDIA_URL[1:]
    else:
        media_url = settings.MEDIA_URL

    # Add the last trailing slash, if have not.
    if not media_url.endswith('/'):
        media_url = media_url + '/'

    urlpatterns += patterns('',
        (r'^' + media_url + '(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

sub/persons/models.py
from django.db import models
from transmeta import TransMeta
from tagging.fields import TagField
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
import os
from django.utils.translation import ugettext_lazy as _
 
def get_image_mugshot_path(instance, filename):
    return os.path.join('headshots', instance.slug, filename)
    
class Person(models.Model):
    
    headshot = models.ImageField(verbose_name=_("Headshot"), upload_to=get_image_mugshot_path, blank=True, null=True)  
    
    creator = models.ForeignKey(User, verbose_name=_("Created by"),
                                blank=True, null=True)
    created = models.DateTimeField(verbose_name=_("Created at"),
                                   auto_now_add=True)
                                   
    slug = models.SlugField(max_length=50, unique=True, blank=True, null=True)
    
    imdb_id = models.PositiveIntegerField(verbose_name=_("IMDB id"), blank=True, null=True)
    imdb_mugshot = models.URLField(verbose_name=_("IMDB Mugshot"),verify_exists=False, blank=True, null=True) 
    imdb_url = models.URLField(verbose_name=_("IMDB Url"),verify_exists=False, blank=True, null=True)
    
    tags = TagField()
    
    class Meta:
        abstract = True
        
class Actor(Person):
    __metaclass__ = TransMeta
    
    name = models.CharField(verbose_name=_("Name"),
                    blank=True, null=False, max_length=250)
                                
    bio = models.TextField(verbose_name=_("Biography"),
                                    blank=True, null=False)
                                    
    def get_absolute_url(self):
        return reverse("actor_item", args=[self.slug])
        
    def save(self, *args, **kwargs):
        self.slug = slugify(getattr(self, 'name_en'))
        super(Person, self).save(*args, **kwargs)  
        
    def __unicode__(self):
        # note that you can use name and description fields as usual
        return self.name

    def __str__(self):
        # compatibility
        return self.__unicode__()
        
    class Meta:
        translate = ('name', 'bio' )

sub/persons/forms.py
from django import forms
from persons.models import Actor
from formfieldset.forms import FieldsetMixin
from django.forms.widgets import HiddenInput

try:
    from django.utils.translation import ugettext_lazy as _
except:
    # if this fails then _ is a builtin
    pass


class ActorForm(forms.ModelForm, FieldsetMixin):
    '''
    Actor Form
    '''
    fieldsets = (
                
                (_('English'),
                  {'fields': ('name_en','bio_en'), }),
                (_('Hebrew'),
                  {'fields': ('name_he','bio_he'), }),
                (_('Russian'),
                  {'fields': ('name_ru','bio_ru'), }),

                  (_('Actor Details'), {'fields': ('tags', 'imdb_id', 'imdb_url','imdb_mugshot' ,'headshot'),
                   'description': _('Your tags are shared')}),
                )
    
    class Meta:
        model = Actor
        exclude = ('slug', 'creator', )
    
    def __init__(self, *args, **kwrds):
        super(ActorForm,self).__init__(*args, **kwrds)
        self.fields['imdb_id'].widget = HiddenInput()
        self.fields['imdb_url'].widget = HiddenInput()
        self.fields['imdb_mugshot'].widget = HiddenInput()
    
    def clean_name(self):
        title = self.cleaned_data['name_en']
        if title == '':
            raise forms.ValidationError(_("name can't be empty"))
        try:
            mobie = Actors.objects.get(name=name)
        except Actors.DoesNotExist:
            return mobie
        raise forms.ValidationError(_('%s already exists') % title )

sub/persons/views.py
# Create your views here.
from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from persons.models import Actor
from persons.forms import ActorForm
from django.core.urlresolvers import reverse
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse
from django.core.files import File
import os
import json
import urllib
from urlparse import urlparse
from datetime import datetime
from imdb import IMDb
from imdb._exceptions import IMDbDataAccessError
from utils.helper import translate_with_wiki
import log
logger = log.get_logger()

def save_mugshot(obj, url):
    '''
    Download a headshot from imdb url, and save it in headshot field for a person
    '''
    f = urllib.urlretrieve(url)
    filetype = urlparse(url).path.split('/')[-1].split('.')[-1]
    filename = "headshot."+filetype
    try:
        os.remove(obj.headshot.path)
    except:
        pass
    obj.headshot.save(filename, File( open(f[0], 'rb') ), save=True)
    
@login_required
def actor_add(request):
    '''
    Add new actor info
    '''  
    
    if request.method == "POST":
        form = ActorForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.creator = request.user
            obj.created = datetime.now()
            obj.save()
            if obj.imdb_mugshot:
                save_mugshot(obj, obj.imdb_mugshot)
            obj.save()
            return HttpResponseRedirect(reverse("actor_item", args=[obj.slug]))
    else:
        form = ActorForm()
        
    template = 'persons/edit.html'
    data = { 'form': form, }
    
    return render_to_response(template, data , context_instance=RequestContext(request))

def actor_edit(request, slug):
    '''
    Edit actor info
    '''
    actor, created = Actor.objects.get_or_create(slug=slug)
    
    if request.method == "POST":
        form = ActorForm(request.POST, request.FILES, instance=actor)
        if form.is_valid():
            obj = form.save(commit=False)
            #todo handle mugshot
            if obj.imdb_mugshot:
                save_mugshot(obj, obj.imdb_mugshot)
            
            obj.save()
            return HttpResponseRedirect(reverse("actor_item", args=[obj.slug]))
    else:
        form = ActorForm(instance=actor)
        
    template = 'persons/edit.html'
    data = { 'form': form, }
    
    return render_to_response(template, data , context_instance=RequestContext(request))
    
@login_required
def actor_delete(request, slug):
    '''
    remove an actor from db
    '''
    if request.is_ajax():
        actor, created = Actor.objects.get_or_create(slug=slug)
        
        try:
            actor.delete()
            return HttpResponse(json.dumps({'success': True, 'slug':slug}))
        except:
            return HttpResponse(json.dumps({'success': False, 'slug':slug}))
    else:
        raise Http404()

@login_required
def imdb_get_info(request, format, person_id):
    '''
    search a person in imdb by it's id
    '''
    if request.is_ajax():
        
        info = {}
        try:
             # set the socket timeout to 1sec
            import socket 
            socket.setdefaulttimeout(5)
            # max retrys on this request
            MAX_RETRY = 3 
            fetch = True
            retries = 0
            while fetch:
                if retries >= MAX_RETRY: break
                try:
                    retries += 1
                    ia = IMDb('http')
                    person = ia.get_person(person_id)
                    fetch = False
                except socket.timeout: logger.warn("timeout") 
                except IOError: logger.warn("timeout") 
                except IMDbDataAccessError: logger.warn("imdb error")
            
            socket.setdefaulttimeout(None)
            try: info['name'] = person['name'].replace(' - IMDb', '')
            except KeyError: pass
            
            try: info['bio'] = person['mini biography']
            except KeyError: pass
            
            try: info['headshot'] = person['headshot'] 
            except KeyError: pass
            
            try: info['imdb_url'] = "http://www.imdb.com/name/nm"+person_id+"/"
            except KeyError: pass
            
            try :  info['birth_date'] = person.data['birth date']
            except KeyError: pass
            
        except: 
            info['error'] = True
            
        if format == 'xml':
            mimetype = 'application/xml'
            #TODO xml serialize
            data = 'Not implemented'
        if format == 'json':
            mimetype = 'application/javascript'
            data = json.dumps(info)

        return HttpResponse(data ,mimetype)
    # If you want to prevent non XHR calls
    else:
        return HttpResponse(status=400)
        
@login_required
def imdb_search_by_name(request, format, name):
    '''
    search an actor in imdb by title, and send back a list with names & imdb ids
    '''
    if request.is_ajax():
        info = {}
        info['list'] = []
        try:
            ia = IMDb('httpThin')
            actors = ia.search_person(name)
            for actor in actors:
                id = actor.personID
                found_name = actor['long imdb canonical name']
                info['list'].append({'id':id, 'name':found_name })
                
        except:
            info['error'] = True
            
        if format == 'xml':
            mimetype = 'application/xml'
            #TODO xml serialize
            data = 'Not implemented'
        if format == 'json':
            mimetype = 'application/javascript'
            data = json.dumps(info)

        return HttpResponse(data ,mimetype)
    # If you want to prevent non XHR calls    
    else:
        return HttpResponse(status=400)
        
@login_required     
def edb_translate_name(request, format, name):
    '''
    translate the actor name into hebrew
    '''
    if request.is_ajax():
        info = {}
        '''
        # set the socket timeout to 1sec
        import socket 
        socket.setdefaulttimeout(1)
        # max retrys on this request
        MAX_RETRY = 3 
        #regex to catch the hebrew name
        regex =r'<div id="title_container">.*?<h1><a.*?>(?P<name>.*?[^<])</a>.*?</div>'
        url="http://www.edb.co.il/find.php?%s"

        params = urllib.urlencode({'s': name.encode('utf-8') })
        logger.debug(url % params) 
        
        fetch = True
        retries = 0
        data = ''
        while fetch:
            if retries >= MAX_RETRY: break
            try: 
                retries += 1
                f = urllib.urlopen(url % params )
                data = f.read()
                fetch = False
            except socket.timeout: pass
            except IOError: pass
        
        #reset 
        socket.setdefaulttimeout(None)
        
        found = re.search(regex, data, re.UNICODE | re.DOTALL)
        if found is not None:
            info['he_name'] = found.group("name")
        else:
            info['error'] = True
        '''
        he_name = translate_with_wiki('he', name)
        if he_name is not None:
            info['he_name'] = he_name.decode('unicode_escape')
        else: 
            info['error'] = True
        if format == 'xml':
            mimetype = 'application/xml'
            #TODO xml serialize
            data = 'Not implemented'
        if format == 'json':
            mimetype = 'application/javascript'
            data = json.dumps(info)

        return HttpResponse(data ,mimetype)
    # If you want to prevent non XHR calls    
    else:
        return HttpResponse(status=400)    

sub/persons/templates/persons/actor_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Details for " %} {{ object.title }}{% endblock %}
{% block extracss %}
    <style>
        {% if LANGUAGE_BIDI %}
        img.headshot{ 
            float: right; 
            margin: 1.5em 1.5em 1.5em 1.5em;
            } 
        {% endif %}
         a.edit{color:red;font-size:40%} 
    </style>
{% endblock %}

{% block content %}
	<h1>{{ object.name }} <a class="edit" href="{{ object.get_absolute_url }}/edit/">[{% trans "Edit" %}]</a> </h1>  
    <p> 
        {% if object.headshot %}
                <img class="headshot" src="{{ object.headshot.url }}"/>
            {% endif %}
        {{ object.bio }}
        {% if object.movie_acted_in %}
            <p> {% trans "Acted in" %}: 
            {% for movie in object.movie_acted_in.all %}
                <a href="{{ movie.get_absolute_url }}"> {{ movie.title }}</a>,
            {% endfor %}
            </p>
        {% endif %}
        
    </p>
    <p>
        {% trans "IMDB ID" %}: 
        <a href="{{ object.imdb_url }}" dir="rtl">{{ object.imdb_id }}</a>
    </p>
{% endblock %}

sub/persons/templates/persons/edit.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Add/Edit Actor Details" %}{% endblock %}
{% block extracss %}
    <style>
        th{ {% if LANGUAGE_BIDI %}text-align: right;{% endif %}
            background: #FFFFFF;
        }
        h2{ {% if LANGUAGE_BIDI %}text-align: right;{% endif %} } 
        input{ {% if LANGUAGE_BIDI %}float: right;{% endif %} }          
        select{ {% if LANGUAGE_BIDI %}float: right;{% endif %} } 
        textarea{ {% if LANGUAGE_BIDI %}float: right;{% endif %} } 
        
        .msg_head {
        cursor: pointer;
        position: relative;
        background:#FFCCCC;
        }
        .msg_body {
        background:#F4F4F8;
        }
        
    </style>
{% endblock %}
{% block extrajs %}
<script type="text/javascript">

$(document).ready(function() { 
	$("span#loading").toggle();
    
    $("tr.msg_body").slice(2,4).toggle();
    $("tr.msg_body").slice(4,8).toggle();
    
    $("tr.msg_head").eq(0).click( function () {
         $("tr.msg_body").slice(0,2).toggle();
    });
    
    $("tr.msg_head").eq(1).click( function () {
         $("tr.msg_body").slice(2,4).toggle();
    });
    
    $("tr.msg_head").eq(2).click( function () {
         $("tr.msg_body").slice(4,6).toggle();
    });
    $("tr.msg_head").eq(3).click( function () {
         $("tr.msg_body").slice(6,10).toggle();
    });


    
    $('button#imdb').click(function () { 
        var name_value = $('input#id_name_en').val();
        var id_value = $('input#id_imdb_id').val();
        
        if (id_value != '') {
            clearErrorsAndMovieList();
            findByID(id_value);
            return
        }
        if (name_value != '') {
            clearErrorsAndMovieList();
            findByName(name_value);
            return
        } else {
            $("div#error").text("English name is empty");
        }
    });
    $('button#translate').click(function () { 
        var name_value = $('input#id_name_en').val();
        if (name_value != '') {
            clearErrors();
            translate_name(name_value);
            return
        } else {
            $("div#error").text("English name is empty");
        }
        
    });
    
    function translate_name(value) {
        $.ajax({
            type: "GET",
            url: "/actors/edb_translate_name/json/"+value+"/",
            dataType:  'json',
            success:   processTranslateData,
            beforeSend:  setLoading, 
            error: processErrors,
        });
    }
    function findByID(value) {
        
        $.ajax({
            type: "GET",
            url: "/actors/imdb_get_info/json/"+value+"/",
            dataType:  'json',
            success:   processActorData,
            beforeSend:  setLoading, 
            error: processErrors,
        });
    }
    
    function processTranslateData(data) {
        if (data.error) {
            $("div#error").text("Error in getting info, try again later...");
        } else {
            $("input#id_name_he").val(data.he_name);
            clearErrors();
        }
        clearLoading();
 
    }
    
    function processActorData(data) {
        if (data.error) {
            $("div#error").text("Error in getting info, try again later...");
        } else {
            $("input#id_name_en").val(data.name);
            $("textarea#id_bio_en").val(data.bio);
            $("input#id_imdb_url").val(data.imdb_url);
            $("input#id_imdb_mugshot").val(data.headshot);
        
        }
        clearLoading();

    }
    
     
    
    function findByName(title) {
        
        $.ajax({
            type: "GET",
            url: "/actors/imdb_search_by_name/json/"+title+"/",
            dataType:  'json',
            success:   processActorList,
            beforeSend:  setLoading, 
            error: processErrors,
        });
    }
    
    function processActorList(data) {
        if (data.error) {
            $("div#error").text("Error in getting info, try again later...");
        } else {
            $.each(data.list, function(i,item){
                    $("<a/>").text(item.name).appendTo("#actorlist").bind("click", {id:item.id},function(e){
                            clearErrors()
                            $("input#id_imdb_id").val(e.data.id);
                            findByID(e.data.id);
                            }).wrap("<li/>");
                    if ( i == 9 ) return false; });
            
            
        }
        clearLoading();
    }
    
    
    function setLoading(data) {
        $("span#loading").toggle();
    }
    function clearLoading() {
        $("span#loading").toggle();
    }
    function clearErrorsAndMovieList() {
        $("div#error").text("");
        $("ol#actorlist").text("");
    }
    function clearErrors() {
        $("div#error").text("");
    }
    
    function processErrors(errors) {
        alert(errors.status )
        alert(errors.responseText )
        $("div#error").text("Error");
        $("div#error").append(errors.responseText);
    }
    


});

</script>
{% endblock %}

{% block content %}
    
    <button type="" id="imdb">{% trans 'Get IMDB Data' %}</button>
    
    <button type="" id="translate">{% trans 'Translate Name' %}</button>
    <span id="loading">
       <img src="{{ MEDIA_URL }}images/loading3.gif" alt="loading..."/> {% trans 'Loading data from IMDB' %} 
    </span>

    <div id="error"></div>  
    <ol id="actorlist"></ol>  
    
    <form enctype="multipart/form-data" action="{{ request.path_info }}" method="post">{% csrf_token %}
        {{ form.errors }}
        <table {% if LANGUAGE_BIDI %}style="float:right"{% endif %} >{{ form.as_fieldset_table }}</table> 
        <input type="submit" value="{% trans 'Save' %}" />
	</form>
    
{% endblock %}