sub/search/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('search.views',
    url(r'^$', 'search', name='search'),
)

sub/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from userprofile.views import get_profiles
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^sub/', include('sub.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
(r'^accounts/', include('userprofile.urls')),
    (r'^$', direct_to_template, {'extra_context': { 'profiles': get_profiles }, 'template': 'front.html'}),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^movies/', include('movies.urls')),
    (r'^actors/', include('persons.urls')),
    (r'^shows/', include('shows.urls')),
    (r'^search/', include('search.urls')),
    (r'^utils/', include('utils.urls')),
    (r'^news/', include('pressroom.urls')),
    (r'^subtitles/', include('subtitles.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),

)
# Serves media content. WARNING!! Only for development uses.
# On production use lighthttpd for media content.
if settings.SERV_STATIC is not None:

    # Delete the first trailing slash, if any.
    if settings.MEDIA_URL.startswith('/'):
        media_url = settings.MEDIA_URL[1:]
    else:
        media_url = settings.MEDIA_URL

    # Add the last trailing slash, if have not.
    if not media_url.endswith('/'):
        media_url = media_url + '/'

    urlpatterns += patterns('',
        (r'^' + media_url + '(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

sub/common-apps/userprofile/models.py
# coding=UTF-8
from django.db import models
from django.contrib.sites.models import Site
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext as _
from django.template import loader, Context
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.conf import settings
from userprofile.countries import CountryField
from django.core.files.storage import default_storage
if hasattr(settings, "AWS_SECRET_ACCESS_KEY"):
    try:
        from backends.S3Storage import S3Storage
        storage = S3Storage()
    except ImportError:
        raise S3BackendNotFound
else:
    storage = default_storage
import datetime
import cPickle as pickle
import base64
import urllib
import os.path
try:
    from PIL import Image, ImageFilter
except ImportError:
    import Image, ImageFilter

AVATAR_SIZES = getattr(settings, 'AVATAR_SIZES', (128, 96, 64, 48, 32, 24, 16))
DEFAULT_AVATAR_SIZE = getattr(settings, 'DEFAULT_AVATAR_SIZE', 96)
if DEFAULT_AVATAR_SIZE not in AVATAR_SIZES:
    DEFAULT_AVATAR_SIZE = AVATAR_SIZES[0]
MIN_AVATAR_SIZE = getattr(settings, 'MIN_AVATAR_SIZE', DEFAULT_AVATAR_SIZE)
DEFAULT_AVATAR = getattr(settings, 'DEFAULT_AVATAR', os.path.join(settings.MEDIA_ROOT, "userprofile", "generic.jpg"))
DEFAULT_AVATAR_FOR_INACTIVES_USER = getattr(settings, 'DEFAULT_AVATAR_FOR_INACTIVES_USER', False)
# params to pass to the save method in PIL (dict with formats (JPEG, PNG, GIF...) as keys)
# see http://www.pythonware.com/library/pil/handbook/format-jpeg.htm and format-png.htm for options
SAVE_IMG_PARAMS = getattr(settings, 'SAVE_IMG_PARAMS', {})

class BaseProfile(models.Model):
    """
    User profile model
    """

    user = models.ForeignKey(User, unique=True)
    creation_date = models.DateTimeField(default=datetime.datetime.now)
    country = CountryField(null=True, blank=True)
    latitude = models.DecimalField(max_digits=10, decimal_places=6, blank=True, null=True)
    longitude = models.DecimalField(max_digits=10, decimal_places=6, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        abstract = True

    def has_avatar(self):
        return Avatar.objects.filter(user=self.user, valid=True).count()

    def __unicode__(self):
        return _("%s's profile") % self.user

    def get_absolute_url(self):
        return reverse("profile_public", args=[self.user])


class Avatar(models.Model):
    """
    Avatar model
    """
    image = models.ImageField(upload_to="avatars/%Y/%b/%d", storage=storage)
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)
    valid = models.BooleanField()

    class Meta:
        unique_together = (('user', 'valid'),)

    def __unicode__(self):
        return _("%s's Avatar") % self.user

    def delete(self):
        if hasattr(settings, "AWS_SECRET_ACCESS_KEY"):
            path = urllib.unquote(self.image.name)
        else:
            path = self.image.path

        base, filename = os.path.split(path)
        name, extension = os.path.splitext(filename)
        for key in AVATAR_SIZES:
            try:
                storage.delete(os.path.join(base, "%s.%s%s" % (name, key, extension)))
            except:
                pass

        super(Avatar, self).delete()

    def save(self, *args, **kwargs):
        for avatar in Avatar.objects.filter(user=self.user, valid=self.valid).exclude(id=self.id):
            if hasattr(settings, "AWS_SECRET_ACCESS_KEY"):
                path = urllib.unquote(self.image.name)
            else:
                path = avatar.image.path

            base, filename = os.path.split(path)
            name, extension = os.path.splitext(filename)
            for key in AVATAR_SIZES:
                try:
                    storage.delete(os.path.join(base, "%s.%s%s" % (name, key, extension)))
                except:
                    pass
            avatar.delete()

        super(Avatar, self).save(*args, **kwargs)


class EmailValidationManager(models.Manager):
    """
    Email validation manager
    """
    def verify(self, key):
        try:
            verify = self.get(key=key)
            if not verify.is_expired():
                verify.user.email = verify.email
                if hasattr(settings, "REQUIRE_EMAIL_CONFIRMATION") and settings.REQUIRE_EMAIL_CONFIRMATION:
                    verify.user.is_active = True
                verify.user.save()
                verify.verified = True
                verify.save()
                return True
            else:
                if not verify.verified:
                    verify.delete()
                return False
        except:
            return False

    def getuser(self, key):
        try:
            return self.get(key=key).user
        except:
            return False

    def add(self, user, email):
        """
        Add a new validation process entry
        """
        while True:
            key = User.objects.make_random_password(70)
            try:
                EmailValidation.objects.get(key=key)
            except EmailValidation.DoesNotExist:
                break

        template_body = "userprofile/email/validation.txt"
        template_subject = "userprofile/email/validation_subject.txt"
        site_name, domain = Site.objects.get_current().name, Site.objects.get_current().domain
        body = loader.get_template(template_body).render(Context(locals()))
        subject = loader.get_template(template_subject).render(Context(locals())).strip()
        send_mail(subject=subject, message=body, from_email=None, recipient_list=[email])
        user = User.objects.get(username=str(user))
        self.filter(user=user).delete()
        return self.create(user=user, key=key, email=email)

class EmailValidation(models.Model):
    """
    Email Validation model
    """
    user = models.ForeignKey(User, unique=True)
    email = models.EmailField(blank=True)
    key = models.CharField(max_length=70, unique=True, db_index=True)
    verified = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    objects = EmailValidationManager()

    def __unicode__(self):
        return _("Email validation process for %(user)s") % { 'user': self.user }

    def is_expired(self):
        if hasattr(settings, 'EMAIL_CONFIRMATION_DELAY'):
            expiration_delay = settings.EMAIL_CONFIRMATION_DELAY
        else:
            expiration_delay = 1
        return self.verified or \
            (self.created + datetime.timedelta(days=expiration_delay) <= datetime.datetime.now())

    def resend(self):
        """
        Resend validation email
        """
        template_body = "userprofile/email/validation.txt"
        template_subject = "userprofile/email/validation_subject.txt"
        site_name, domain = Site.objects.get_current().name, Site.objects.get_current().domain
        key = self.key
        body = loader.get_template(template_body).render(Context(locals()))
        subject = loader.get_template(template_subject).render(Context(locals())).strip()
        send_mail(subject=subject, message=body, from_email=None, recipient_list=[self.email])
        self.created = datetime.datetime.now()
        self.save()
        return True

class UserProfileMediaNotFound(Exception):
    pass

class S3BackendNotFound(Exception):
    pass

class GoogleDataAPINotFound(Exception):
    pass

sub/common-apps/userprofile/forms.py
from django import forms
from django.core.exceptions import ObjectDoesNotExist
from django.core.exceptions import ImproperlyConfigured
from django.db import models
from django.utils.translation import ugettext as _
from django.conf import settings
from django.contrib.auth.models import User, SiteProfileNotAvailable
from userprofile.models import EmailValidation, AVATAR_SIZES, DEFAULT_AVATAR_SIZE, MIN_AVATAR_SIZE
from django.core.files.uploadedfile import SimpleUploadedFile
import mimetypes, urllib
from django.contrib.auth.forms import UserCreationForm

if not settings.AUTH_PROFILE_MODULE:
    raise SiteProfileNotAvailable
try:
    app_label, model_name = settings.AUTH_PROFILE_MODULE.split('.')
    Profile = models.get_model(app_label, model_name)
except (ImportError, ImproperlyConfigured):
    raise SiteProfileNotAvailable

class LocationForm(forms.ModelForm):
    """
    Profile location form
    """

    class Meta:
        model = Profile
        fields = ('location', 'latitude', 'longitude', 'country')

class ProfileForm(forms.ModelForm):
    """
    Profile Form. Composed by all the Profile model fields.
    """
    class Meta:
        model = Profile
        exclude = ('creation_date', 'location', 'latitude', 'longitude', 'country',
                   'user', 'public', 'site')

class PublicFieldsForm(forms.ModelForm):
    """
    Public Fields of the Profile Form. Composed by all the Profile model fields.
    """
    class Meta:
        model = Profile
        exclude = ('creation_date', 'user', 'public')

class AvatarForm(forms.Form):
    """
    The avatar form requires only one image field.
    """
    photo = forms.ImageField(required=False, help_text=_("Select an image from disk"))
    url = forms.URLField(required=False, help_text=_("Select an image from a remote URL. Put the URL on the input below and we'll retrieve the image for you"))

    def clean_url(self):
        url = self.cleaned_data.get('url')
        if not url: return ''
        try:
            filename, headers = urllib.urlretrieve(url)
        except:
            raise forms.ValidationError(forms.fields.URLField.default_error_messages['invalid_link'])
        if not mimetypes.guess_all_extensions(headers.get('Content-Type')):
            raise forms.ValidationError(_('The file type is invalid: %s' % type))
        return SimpleUploadedFile(filename, open(filename).read(), content_type=headers.get('Content-Type'))

    def clean(self):
        if not (self.cleaned_data.get('photo') or self.cleaned_data.get('url')):
            raise forms.ValidationError(_('You must enter one of the options'))
        return self.cleaned_data

class AvatarCoordinateField(forms.IntegerField):
    def clean(self, value):
        try:
            value = int(float(value))
        except:
            pass
        return super(AvatarCoordinateField, self).clean(value)

class AvatarCropForm(forms.Form):
    """
    Crop dimensions form
    """
    top = AvatarCoordinateField()
    bottom = AvatarCoordinateField()
    left = AvatarCoordinateField()
    right = AvatarCoordinateField()

    def __init__(self, image=None, *args, **kwargs):
        self.image = image
        super(AvatarCropForm, self).__init__(*args, **kwargs)

    def clean(self):
        if self.cleaned_data.get('right') and self.cleaned_data.get('left') and \
           int(self.cleaned_data.get('right')) - int(self.cleaned_data.get('left')) < MIN_AVATAR_SIZE:
            raise forms.ValidationError(_("You must select a portion of the image with a minimum of %(min_avatar_size)dx%(min_avatar_size)d pixels.") % { 'min_avatar_size': MIN_AVATAR_SIZE })

        return self.cleaned_data



class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=getattr(settings, "REQUIRE_EMAIL_CONFIRMATION", False), label=_("E-mail address"))

    class Meta:
        model = User
        fields = ("username","email",)

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")

        if not email: return  email

        try:
            User.objects.get(email__iexact=email)
            raise forms.ValidationError(_("That e-mail is already used."))
        except User.DoesNotExist:
            try:
                EmailValidation.objects.get(email=email)
                raise forms.ValidationError(_("That e-mail is already being confirmed."))
            except EmailValidation.DoesNotExist:
                return email

    def save(self, *args, **kwargs):
        user = super(RegistrationForm, self).save(commit=False)
        user.is_active = not getattr(settings, "REQUIRE_EMAIL_CONFIRMATION", False)
        user.save()
        if self.cleaned_data.get('email'):
            EmailValidation.objects.add(user=user, email=user.email)
        return user

try:
    _temp = settings.REGISTRATION_FORM.split('.')
    _form_class = _temp.pop()
    _module = __import__('.'.join(_temp), globals(), locals(), [_form_class])
    _RegistrationForm = getattr(_module, _form_class)
except:
    _RegistrationForm = RegistrationForm

class EmailValidationForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")
        if not (User.objects.filter(email=email) or EmailValidation.objects.filter(email=email)):
            return email

        raise forms.ValidationError(_("That e-mail is already used."))

class ResendEmailValidationForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        """
        Verify that the email exists
        """
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email) or EmailValidation.objects.filter(email=email):
            return email

        raise forms.ValidationError(_("That e-mail isn't registered."))

sub/search/views.py
# Create your views here.
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from movies.models import Movie
from persons.models import Actor

from search.index import complete_indexer
from django import forms

try:
    from django.utils.translation import ugettext_lazy as _
except:
    # if this fails then _ is a builtin
    pass
    
MODEL_MAP = {
    'movie': Movie,
    'actor': Actor,
}

MODEL_CHOICES = [('', 'all')] + zip(MODEL_MAP.keys(), MODEL_MAP.keys())

class SearchForm(forms.Form):
    query = forms.CharField(label=_("Query"), required=True)
    model = forms.ChoiceField(label=_("Type"), choices=MODEL_CHOICES, required=False)
    
def search(request):
    results = []

    if request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            model = MODEL_MAP.get(form.cleaned_data['model'])

            if not model:
                indexer = complete_indexer
            else:
                indexer = model.indexer

            results = indexer.search(query)
            #.prefetch()
            
            print [str(x) for x in results]
    else:
        form = SearchForm()

    return render_to_response('search/search.html', {'results': results, 'form': form}, context_instance=RequestContext(request))

sub/templates/userprofile/avatar/choose.html
{% extends "base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Choose the location of your avatar" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
<script type="text/javascript">
	$(function() {
	//avatar
		$("a.delavatar").click(function() {
			$.getJSON($(this).attr("href"), function(data) {
				if (data.success) {
					$("img#avatarimg").attr("src", "{{ generic96 }}");
					$("p#avatardelete").remove();
				}
			});
			return false;
		});
	});
</script>
{% endblock %}

{% block nav-main %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block content %}
	<form action="" method="post" accept-charset="utf-8" enctype="multipart/form-data">{% csrf_token %}
		{% if form.errors %}
			{% for error,desc in form.errors.items %}
				<p class="error">{{desc|join:"; "}}</p>
			{% endfor %}
		{% endif %}
		<fieldset>
			<legend>{% trans "Choose the location of your avatar" %}</legend>
			<ul>
			<li>
				<label for="id_photo">{% trans "Select an image from disk" %}:</label>
				<p>{{ form.photo }}
				<input type="submit" value="{% trans 'Done' %}" />
				</p>
			</li>
			<li>
				<label for="id_url">{% trans "Select an image from a remote URL. Put the URL on the input below and we'll retrieve the image for you" %}:</label>
				<p>{{ form.url }}
				<input type="submit" value="{% trans 'Done' %}" />
				</p>
			</li>
			{% if AVATAR_WEBSEARCH %}
			<li>
				<a class="large" href="{{ request.path_info }}search/">{% trans "Search for an image on Picasa Web" %}</a>
			</li>
			{% endif %}
			</ul>
		</fieldset>
		</form>
{% endblock %}

{% block content-related %}
  <div class="box">
    <h3>{% trans "Avatar selection page" %}</h3>
		<p>{% trans "You have several options to select the image you want as avatar on your profile" %}.</p>
  </div>

	{% load avatars %}
  <div class="center">
		<img class="border" id="avatarimg" src="{% avatar 96 %}" />
    {% if user.get_profile.has_avatar %}<p id="avatardelete" style="text-align: center;"><a href="{{ request.path_info }}delete/" class="delavatar">{% trans "Delete" %}</a></p>{% endif %}
	</div>
{% endblock %}

sub/templates/userprofile/avatar/crop.html
{% extends "base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Crop &amp; resize the area you want" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.imgareaselect-0.4.2.min.js"></script>
<script type="text/javascript">
	$(function() {
		function updateValues(img, selection) {
			$("input[name='left']").val(selection.x1);
			$("input[name='top']").val(selection.y1);
			$("input[name='right']").val(selection.x2);
			$("input[name='bottom']").val(selection.y2);
		}
		$(window).load(function() {
			$("#cropimage").imgAreaSelect({ aspectRatio: "1:1", onSelectEnd: updateValues });
		});
	});
</script>
{% endblock %}

{% block nav-main %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block content %}
	<form action="{{ request.path_info }}" method="post" accept-charset="utf-8">{% csrf_token %}
	<fieldset>
		<legend>{% trans "Crop &amp; resize the area you want" %}</legend>

		{% if form.errors %}
			{% for error,desc in form.errors.items %}
				<p class="error">{{desc|join:"; "}}</p>
			{% endfor %}
		{% endif %}

		<div style="text-align: center;">
			<img src="{{ avatar.image.url }}" id="cropimage" />
		</div>
		<input type="hidden" name="top" value="0"/>
		<input type="hidden" name="bottom" value="0"/>
		<input type="hidden" name="left" value="0"/>
		<input type="hidden" name="right" value="0"/>
	</fieldset>
	<input type="submit" class="done" value="{% trans 'Done' %}" />
	</form>
{% endblock %}

{% block content-related %}
  <div class="box">
    <h3>{% trans "Avatar selection page" %}</h3>
    <p>{% trans "You have several options to select the image you want as avatar on your profile" %}.</p>
  </div>

  {% load avatars %}
  <div class="center">
    <img class="border" id="avatarimg" src="{% avatar 96 %}" />
  </div>

{% endblock %}

sub/templates/userprofile/avatar/done.html
{% extends "base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Avatar selection finished" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block nav-main %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block content %}
	<p class="success large">
		{% trans "Your new avatar has been saved successfully" %}.
	</p>
{% endblock %}

{% block content-related %}
  <div class="box">
    <h3>{% trans "Avatar selection page" %}</h3>
    <p>{% trans "You have several options to select the image you want as avatar on your profile" %}.</p>
  </div>

  {% load avatars %}
  <div class="center">
    <img class="border" id="avatarimg" src="{% avatar 96 %}" />
  </div>

{% endblock %}

sub/templates/userprofile/avatar/search.html
{% extends "base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Search for an image on Picasa Web" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block extrajs %}
<script type="text/javascript">
	$(function() {
		$("input[type='text']").focus();
		$("input[type='text']").addClass("text");
		$("div.photos a").click(function() {
			$("form#avatar input[name='url']").val($(this).attr("href"));
			$("form#avatar").submit();
			return false;
		});
	});
</script>
{% endblock %}

{% block nav-main %}
{% include "userprofile/menu.html" %}
{% endblock %}

{% block content %}
	<form action="" method="post" accept-charset="utf-8">{% csrf_token %}
	<fieldset>
		<legend>{% trans "Search for an image on Picasa Web" %}</legend>
		<label for="id_search">{% trans "Search on Picasa Web" %}</label>
		<p>
			<input type="text" name="keyword" value="{{ keyword }}" />
			<input type="submit" value="{% trans "Search" %}"/>
		</p>

		<div class="photos">
			{% for thumb,url in images.items %}
			<a href="{{ url }}"><img src="{{ thumb }}" /></a>
			{% endfor %}
		</div>
	</fieldset>
	</form>

	<form class="hide" id="avatar" action="{% url profile_edit_avatar %}" method="post" accept-charset="utf-8">{% csrf_token %}
		<input type="hidden" name="url" value="" />
	</form>
{% endblock %}

{% block content-related %}
  <div class="box">
    <h3>{% trans "Avatar selection page" %}</h3>
    <p>{% trans "You have several options to select the image you want as avatar on your profile" %}.</p>
  </div>

  {% load avatars %}
  <div class="center">
    <img class="border" id="avatarimg" src="{% avatar 96 %}" />
  </div>

{% endblock %}